// <auto-generated />
namespace NaaBook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Fullnamestudent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fullnamestudent));
        
        string IMigrationMetadata.Id
        {
            get { return "201906062009467_Fullnamestudent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
